export default [
  {
    title: 'Sự kiện Gia đình',
    date: ['12/12/2023', '12/12/2023'],
    id: 1,
    label: 'success',
    time: ['2:00 pm', '3:00 pm'],
    type: 'event',
    description: 'Đây là một sự kiện gia đình quan trọng với nội dung miêu tả chi tiết.',
  },
  {
    title: 'Ra mắt Sản phẩm',
    date: ['13/12/2023', '13/12/2023'],
    id: 2,
    label: 'primary',
    time: ['4:00 pm', '5:00 pm'],
    type: 'reminder',
    description: 'Sự kiện quan trọng này là cơ hội để giới thiệu sản phẩm mới của chúng tôi.',
  },
  {
    title: 'Cuộc họp nhóm',
    id: 3,
    date: ['14/12/2023', '14/12/2023'],
    label: 'secondary',
    time: ['2:00 pm', '3:00 pm'],
    type: 'event',
    description: 'Cuộc họp nhóm sẽ diễn ra để thảo luận về các vấn đề quan trọng.',
  },
  {
    title: 'Nhiệm vụ UI/UX',
    id: 4,
    date: ['12/12/2023', '12/12/2023'],
    label: 'info',
    time: ['9:10 am', '3:10 pm'],
    type: 'event',
    description: 'Nhiệm vụ này tập trung vào phát triển giao diện người dùng và trải nghiệm người dùng.',
  },
  {
    title: 'Cập nhật Dự án',
    id: 5,
    date: ['11/12/2023', '11/12/2023'],
    label: 'warning',
    time: ['12:00 pm', '2:30 pm'],
    type: 'event',
    description: 'Cập nhật về tiến độ dự án và các vấn đề cần chú ý trong buổi họp này.',
  },
  {
    title: 'Họp Nhóm Marketing',
    date: ['15/12/2023', '15/12/2023'],
    id: 6,
    label: 'info',
    time: ['10:00 am', '12:00 pm'],
    type: 'meeting',
    description: 'Cuộc họp này nhằm xác định chiến lược tiếp thị cho dự án mới.',
  },
  {
    title: 'Lịch Sử Doanh Nghiệp',
    date: ['16/12/2023', '16/12/2023'],
    id: 7,
    label: 'warning',
    time: ['1:30 pm', '3:30 pm'],
    type: 'event',
    description: 'Dự kiến sẽ có một sự kiện giới thiệu về lịch sử và thành tựu của công ty.',
  },
  {
    title: 'Tổng Kết Tháng',
    id: 8,
    date: ['17/12/2023', '17/12/2023'],
    label: 'success',
    time: ['4:00 pm', '5:30 pm'],
    type: 'meeting',
    description: 'Cuộc họp cuối tháng để đánh giá tiến độ công việc và kế hoạch cho tháng kế tiếp.',
  },
  {
    title: 'Triển lãm Sản phẩm',
    id: 9,
    date: ['18/12/2023', '18/12/2023'],
    label: 'primary',
    time: ['9:00 am', '6:00 pm'],
    type: 'event',
    description: 'Tham gia triển lãm để trưng bày sản phẩm và tạo mối quan hệ với đối tác.',
  },
  {
    title: 'Bảo trì Hệ thống',
    id: 10,
    date: ['20/12/2023', '20/12/2023'],
    label: 'primary',
    time: ['12:00 pm', '3:00 pm'],
    type: 'reminder',
    description: 'Bảo trì hệ thống để đảm bảo hoạt động ổn định và hiệu suất cao.',
  },
  {
    title: 'Cuộc họp Chiến lược',
    id: 11,
    date: ['21/12/2023', '21/12/2023'],
    label: 'info',
    time: ['2:30 pm', '4:00 pm'],
    type: 'meeting',
    description: 'Thảo luận về chiến lược dài hạn và các mục tiêu kinh doanh.',
  },
  {
    title: 'Tổ chức Đào tạo Nhân sự',
    id: 12,
    date: ['22/12/2023', '22/12/2023'],
    label: 'warning',
    time: ['10:00 am', '12:00 pm'],
    type: 'event',
    description: 'Đào tạo nhân sự về các chính sách mới và kỹ năng cần thiết.',
  },
  {
    title: 'Chia sẻ Tiến độ Dự án',
    id: 13,
    date: ['23/12/2023', '23/12/2023'],
    label: 'success',
    time: ['3:00 pm', '4:30 pm'],
    type: 'meeting',
    description: 'Báo cáo về tiến độ dự án và đánh giá hiệu suất nhóm.',
  },
  {
    title: 'Thực Hiện Thử nghiệm',
    id: 14,
    date: ['24/12/2023', '24/12/2023'],
    label: 'primary',
    time: ['1:00 pm', '3:00 pm'],
    type: 'event',
    description: 'Thực hiện thử nghiệm cho sản phẩm mới trước khi ra mắt.',
  },
  {
    title: 'Lễ Tưởng Nhớ',
    id: 15,
    date: ['25/12/2023', '25/12/2023'],
    label: 'primary',
    time: ['11:00 am', '12:30 pm'],
    type: 'event',
    description: 'Tham gia lễ tưởng nhớ và chia sẻ niềm kính trọng.',
  },
];
